# NumPy Lab 2: Aggregation, Axis, and Masks

*Shreyup Bhandari*  
*DSC270*  
*11th September, 2026*

**This lab needs two files.** You downloaded the notebook and `student_scores.csv` from Moodle. Make sure both are in the same folder, and that you opened the notebook from that folder. The setup cell reads the file.

**Do not delete the instruction cells.** Add your solutions, in Markdown or code as each task requires, in new cells below each instruction. Each task names the variables it wants. Use those names exactly, because we check for them.

## Task 1: Predict Before You Run

Same as the earlier labs. For each of the three code cells below, edit the *My prediction* cell above it and write what you expect the output to be, then run the code and compare. If you were wrong, leave your prediction and add one sentence saying what surprised you. One line is enough. A wrong prediction with one sentence earns full credit.

*My prediction (edit this cell):* [5 7 9] [6 15]

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


*My prediction (edit this cell):* 95 1

In [2]:
b = np.array([40, 95, 70, 95])
print(b.max())
print(b.argmax())

95
1


*My prediction (edit this cell):* [3 4 5 6] 4

In [3]:
print(a[a > 2])
print((a > 2).sum())

[3 4 5 6]
4


## Setup

Run the cell below. It loads the file into an array named `data`.

- Each row is one student. There is no header row.
- The first column is the student's ID. The other seven columns are scores on Tests 1 through 7.
- You will not be asked to write `np.loadtxt`. Two weeks from now pandas replaces it.

If you get a `FileNotFoundError`, the file is not beside the notebook. Fix that before going on; Lab 4 showed how.

In [4]:
import numpy as np

data = np.loadtxt("student_scores.csv", delimiter=",", dtype=int)
data

array([[10210,    83,    79, ...,    76,    78,    79],
       [10252,    61,    63, ...,    63,    62,    62],
       [10340,    94,    89, ...,    84,    87,    90],
       ...,
       [98500,   100,    96, ...,    91,    93,    96],
       [98706,    73,    73, ...,    72,    71,    73],
       [98903,    77,    76, ...,    74,    74,    75]], shape=(300, 8))

## Task 2: Shape and First Rows

In a new code cell:

1. `n_students` and `n_tests`: how many students and how many tests, taken from `data.shape`. Do not count the ID column as a test. Print both in one f-string sentence.
2. `first_five`: the first five rows of `data`, IDs included. Print it.

In [5]:
n_students=data.shape[0]
n_tests=data[:,1:].shape[1]
print(f"There are {n_students} students and {n_tests} tests in total.")
first_five=data[:5,:]
print(first_five)


There are 300 students and 7 tests in total.
[[10210    83    79    78    76    76    78    79]
 [10252    61    63    61    63    63    62    62]
 [10340    94    89    87    84    84    87    90]
 [10492    83    80    78    76    77    78    80]
 [10934   100    96    92    90    90    93    95]]


## Task 3: Averages by Student

In a new code cell:

1. `scores`: every row of `data` and every column except the first. This drops the IDs, and every later task uses it.
2. `first_five_avg`: the average score of each of the first five students, across all seven tests. One line, using `axis=`. Print it rounded to one decimal place.

Check yourself: five numbers, each between 0 and 100. If you got seven numbers, or numbers in the thousands, the axis or the columns are wrong.

In [6]:
scores=data[:,1:]
first_five_avg=scores[:5,:].mean(axis=1)
first_five_avg.round(1)

array([78.4, 62.1, 87.9, 78.9, 93.7])

## Task 4: Statistics by Test

This task is about all 300 students, not the first five.

In a new code cell, compute five arrays over `scores`, one value per test: `test_min`, `test_max`, `test_mean`, `test_median`, and `test_std`. Each is one line with `axis=`.

Then copy this loop into the same cell, below your five lines, and run it:

```python
for i in range(7):
    print(f"Test {i + 1}: min={test_min[i]}, max={test_max[i]}, "
          f"mean={test_mean[i]:.1f}, median={test_median[i]}, std={test_std[i]:.1f}")
```

Check yourself: every max is 100.

In [7]:
test_min=scores.min(axis=0)
test_max=scores.max(axis=0)
test_mean=scores.mean(axis=0)
test_median=np.median(scores,axis=0)
test_std=scores.std(axis=0)
test_max


array([100, 100, 100, 100, 100, 100, 100])

In [8]:
for i in range(7):
    print(f"Test {i + 1}: min={test_min[i]}, max={test_max[i]}, "
          f"mean={test_mean[i]:.1f}, median={test_median[i]}, std={test_std[i]:.1f}")

Test 1: min=39, max=100, mean=84.2, median=85.0, std=11.3
Test 2: min=57, max=100, mean=81.2, median=81.0, std=9.2
Test 3: min=53, max=100, mean=79.3, median=79.0, std=8.7
Test 4: min=60, max=100, mean=77.7, median=77.0, std=8.0
Test 5: min=59, max=100, mean=78.3, median=78.0, std=7.3
Test 6: min=56, max=100, mean=79.5, median=80.0, std=9.0
Test 7: min=46, max=100, mean=80.8, median=81.0, std=9.9


## Task 5: Which Students?

Which students scored 90 or above on Test 1?

In a new code cell:

1. `mask`: a mask with one `True` or `False` per student, `True` where the Test 1 score is 90 or above. Test 1 is the first column of `scores`.
2. `n_high`: how many students that is. Print it.
3. `high_test1`: the ID and Test 1 score of the **first ten** of those students, in the order they appear in the file. Apply the mask to `data` (so the IDs come along), then slice. Print it.

Do not sort anything in this task.

In [9]:
mask=scores[:,0]>90
n_high=scores[:,0][mask]
print(n_high)
print(len(n_high))
high_test1=data[:,:2][mask][:10]
high_test1

[ 94 100  96  94  95  92 100 100  95 100 100  93 100 100 100  96  92 100
 100  98 100 100 100  91  93  94  97 100 100  93  94  97 100 100  93  98
 100  93  91 100 100  98 100 100  95  91 100 100  93  95  97 100 100  91
  98  97  92  94 100  93  92  93  94  91  92  99  93  99  93 100 100  92
  96  95 100  91 100 100  95  94  92  92 100  94 100  94  96 100  91  93
  92  95 100 100  92 100 100  92  96  92 100]
101


array([[10340,    94],
       [10934,   100],
       [11146,    96],
       [11311,    94],
       [12245,    95],
       [13270,    92],
       [13859,   100],
       [14116,   100],
       [14271,    95],
       [14339,   100]])

## Task 6: The Top Ten Averages

In a new code cell:

1. `student_avg`: every student's average across the seven tests. Same idea as Task 3, all rows this time.
2. `top_averages`: the ten highest averages, highest first. `np.sort` puts them lowest first; a slice with a step of -1, `arr[::-1]`, reverses an array.
3. Print `top_averages` rounded to one decimal place.

Which students those are is a different question, and it needs a tool from Monday. Here we want only the numbers.

In [10]:
student_avg=scores.mean(axis=1)
top_averages=np.sort(student_avg)[::-1][:10]
print(top_averages.round(1))

[100.   99.1  98.9  98.7  98.3  97.9  97.4  96.4  96.3  96. ]


## Task 7: any and all

Two questions about the whole class. Answer each with code, then a printed sentence, in a new code cell.

**7a.** Did any student score 100 on every test? Build `perfect`, a mask with one entry per student that is `True` for a student whose seven scores are all 100. Then `any_perfect`, a single `True` or `False`. Print a sentence with the answer. If the answer is yes, also print the ID of every such student (apply `perfect` to `data` and take the first column).

**7b.** Does every test have at least one score of 100 *and* at least one score below 60? Build `has_100` and `has_low`, one entry per test each, combine them with `&`, and reduce with `.all()` into `both_all`. Print `has_100`, `has_low`, and a sentence with the answer.

Then, in a Markdown cell, one sentence: if the answer to 7b is no, which test fails, and which of the two conditions does it fail?

In [11]:
perfect=np.all(scores==100,axis=1)
any_perfect=np.any(scores==100,axis=1)
print(f"The id of those who scored a 100 in all tests:\n{data[:,0][perfect]}")
print(f"The id of those who scored a 100 in any test:\n{data[:,0][any_perfect]}")

The id of those who scored a 100 in all tests:
[14339]
The id of those who scored a 100 in any test:
[10934 13859 14116 14339 15758 16995 17184 17737 19925 20791 23412 24217
 24379 27281 27442 30320 31508 38084 39708 41823 44532 45249 46679 47368
 48708 49853 58676 65893 66332 71523 72115 73092 77867 79154 83439 91182
 92809 96577 96795 98500]


7a. Yes, there was a student who scored a 100 on all tests whose id is displayed above along with student who got a 100 in at least one of the 7 tests.

In [12]:
has_100=(scores==100).any(axis=0)
has_low=np.any(scores<60,axis=0)
both_all=has_100 & has_low
print(has_100)
print(has_low)
print(both_all)
print(f"Test 4 has at least one score of 100 but doesnt have a score below 60.")

[ True  True  True  True  True  True  True]
[ True  True  True False  True  True  True]
[ True  True  True False  True  True  True]
Test 4 has at least one score of 100 but doesnt have a score below 60.


Test 4 fails- it satisfies the condition for having a score of 100, but doesn't meet the criteria of having a score below 60.

## Task 8: Check This Code

The cell below was written to print the five highest student averages, highest first. It runs without an error.

Run it. Then, in a Markdown cell, say whether the output can be right, what is wrong with the code, and which of the four questions from Monday catches it. Then fix it in a new code cell, naming the corrected averages `averages_fixed`, and print the five highest.

In [13]:
# Average score for each student, highest first
averages = data.mean(axis=1)
print(np.sort(averages)[::-1][:5])

[12428.25  12401.25  12395.    12370.125 12326.125]


Even though the program does not crash, the average is incorrect since it also includes the id of the students while computing the averages.

In [14]:
averages_fixed=scores.mean(axis=1)
print(np.sort(averages_fixed)[::-1][:5])

[100.          99.14285714  98.85714286  98.71428571  98.28571429]


## Challenge (optional): The Biggest Drop

Only if you have time. Compare each student's average on Tests 1 and 2 with their average on Tests 6 and 7. Compute `drop`, early average minus late average, one value per student. Print the largest drop, then print the IDs of every student whose drop equals it. A mask does this; no sorting needed.

In [15]:
early_average=scores[:,:2].mean(axis=1)
late_average=scores[:,5:].mean(axis=1)
drop=early_average-late_average
drop_mask=drop==drop.max()
print(f"The ids of those who had the highest drop:\n{data[:,0][drop_mask]}")




The ids of those who had the highest drop:
[81384]


## Final Check: Restart and Run All

1. Before you finish this lab, restart the kernel and run all cells to make sure everything still works. (Hint: there is a single command that does this.)
2. Check that every output is what you expect.
3. Upload the notebook to Moodle, and keep a copy in your own OneDrive.

If you finish the lab outside of class, we are still glad to see it. Show us during the next lab hour if you like.

### General Instructions for Labs

- If you do not finish during the lab hour, complete it as homework. **Labs are due at the start of the next class session.**
- A late lab earns reduced credit, capped at 60. Late work is accepted until the start of class on the day of the test covering this module, and not after.
- A file that is empty, corrupted, or will not open is not a submission. Replace it within 24 hours and it earns credit as late work.
- Moodle carries the official deadline. If a deadline ever changes, the change appears on Moodle first.