# NumPy Lab 1: Arrays and Vectorized Operations

*Shreyup Bhandari*  
*DSC270*  
*9th Septemeber, 2026*

There is no data file for this lab. Everything is typed in.

**Do not delete the instruction cells.** Add your solutions, in Markdown or code as each task requires, in new cells below each instruction. Each task names the variables it wants. Use those names exactly, because we check for them.

Run this cell first. Every other cell in the lab assumes it has run.

In [1]:
import numpy as np

## Task 1: Predict Before You Run

Same as Labs 3 through 6. For each of the three code cells below, edit the *My prediction* cell above it and write what you expect the output to be, then run the code and compare. If you were wrong, leave your prediction and add one sentence saying what surprised you. One line is enough. A wrong prediction with one sentence earns full credit.

*My prediction (edit this cell):*[2 4 6] [1,2,3,1,2,3]

In [2]:
a = np.array([1, 2, 3])
print(a * 2)
print([1, 2, 3] * 2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


*My prediction (edit this cell):* [10 99 30 40]

In [3]:
arr = np.array([10, 20, 30, 40])
part = arr[1:3]
part[0] = 99
print(arr)

[10 99 30 40]


*My prediction (edit this cell):* [1. 2.5 3.] float64

In [4]:
b = np.array([1, 2.5, 3])
print(b)
print(b.dtype)

[1.  2.5 3. ]
float64


## Task 2: Cost Times Quantity

Ten orders at a campus coffee counter. The first list is the cost of one item, the second is how many were bought. Run the cell below to load them.

In [5]:
costs = [3.25, 12.99, 7.50, 1.99, 24.00, 5.75, 9.49, 15.00, 2.50, 8.25]
quantities = [4, 1, 2, 10, 1, 3, 2, 1, 6, 2]

**2a. With NumPy, and no loops.** In a new code cell:

1. Make a 10 by 3 array of zeros named `orders`.
2. Put the costs in the first column and the quantities in the second column. A slice on the left of `=` assigns to a whole column: `orders[:, 0] = costs`.
3. Fill the third column with the subtotal, cost times quantity, using the first two columns.
4. Print `orders` and print `orders.shape`.

Check yourself: the first subtotal is 13.0 and the last is 16.5.

**2b. With plain Python, and loops.** In a new code cell, build the same table as a nested list named `orders_list`: ten rows, each a list of cost, quantity, and subtotal. Start from an empty list and use a loop over `range(10)`. Round each subtotal to two places. Print `orders_list`.

**2c. Compare.** In a new Markdown cell, two or three sentences: which version was shorter, which was easier to read, and where you would be most likely to make a mistake in each.

In [6]:
orders=np.zeros((10,3))
orders[:,0]=costs
orders[:,1]=quantities
orders[:,2]=orders[:,0]*orders[:,1]
print(orders)
print(orders.shape)

[[ 3.25  4.   13.  ]
 [12.99  1.   12.99]
 [ 7.5   2.   15.  ]
 [ 1.99 10.   19.9 ]
 [24.    1.   24.  ]
 [ 5.75  3.   17.25]
 [ 9.49  2.   18.98]
 [15.    1.   15.  ]
 [ 2.5   6.   15.  ]
 [ 8.25  2.   16.5 ]]
(10, 3)


In [7]:
orders_list=[]
row=[]
for i in range(10):
    row.append(costs[i])
    row.append(quantities[i])
    row.append(round(costs[i]*quantities[i],2))
    orders_list.append(row)
    row=[]
print(orders_list)


[[3.25, 4, 13.0], [12.99, 1, 12.99], [7.5, 2, 15.0], [1.99, 10, 19.9], [24.0, 1, 24.0], [5.75, 3, 17.25], [9.49, 2, 18.98], [15.0, 1, 15.0], [2.5, 6, 15.0], [8.25, 2, 16.5]]


The python version much more tedious and prone to error as it involves creating an empty list and then appending new rows on every loop.

## Task 3: Making Arrays

In one new code cell, make these six arrays and print each one. Run the seed line first, exactly as written, so your random numbers match ours.

```python
np.random.seed(270)
```

1. `zero_array`: a 5 by 5 array of zeros.
2. `ones_array`: 10 ones.
3. `full_tens`: 15 elements, all 10.
4. `sequence_array`: 0 up to 20 in steps of 2, using `np.arange`.
5. `linspace_array`: 9 evenly spaced values from 0 to 1. Print its `.shape` as well to confirm the count.
6. `random_ints`: a 3 by 3 array of random integers from 1 through 100, 100 included, using `np.random.randint`. Remember that the stop value is left out.

In [8]:
np.random.seed(270)
zero_array=np.zeros((5,5))
print(zero_array)
ones_array=np.ones(10)
print(ones_array)
full_tens=np.full(15,10)
print(full_tens)
sequence_array=np.arange(0,20,2)
print(sequence_array)
linspace_array=np.linspace(0,1,9)
print(linspace_array)
print(linspace_array.shape)
random_ints=np.random.randint(1,101,(3,3))
print(random_ints)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
[ 0  2  4  6  8 10 12 14 16 18]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
(9,)
[[33 73 24]
 [48  7 76]
 [28 54 21]]


## Task 4: Indexing and Slicing

Working with `random_ints` from Task 3, in a new code cell:

1. `corner`: the element in the second row, third column. Print it.
2. `middle_row`: the second row, all columns. Print it.
3. `last_col`: the last column, all rows. Print it.
4. Add 20 to every element in the **second column** of `random_ints`, and only that column. Then print `random_ints`.

Check yourself: after step 4, the first and third columns are what they were.

In [9]:
corner=random_ints[1,2]
print(corner)
middle_row=random_ints[1,:]
print(middle_row)
last_col=random_ints[:,2]
print(last_col)
second_column=random_ints[:,1]
second_column+20
print(second_column)


76
[48  7 76]
[24 76 21]
[73  7 54]


## Task 5: Slices Are Views

In a new code cell:

1. `block`: the 2 by 2 sub-array in the bottom-right corner of `random_ints` (the last two rows and the last two columns).
2. Multiply `block` by 2 in place with `block *= 2`, then print `block` and print `random_ints`.
3. In a Markdown cell, one sentence: what happened to `random_ints`, and why.
4. In a second code cell, make `safe`, the same 2 by 2 corner but with `.copy()` on the end. Multiply `safe` by 2 in place, then print `random_ints` to show it did not change this time.

In [10]:
block=random_ints[1:,1:]
block*=2
print(block)
print(random_ints)

[[ 14 152]
 [108  42]]
[[ 33  73  24]
 [ 48  14 152]
 [ 28 108  42]]


## Task 6: Arithmetic and Functions

In a new code cell:

1. `num_array`: add a 3 by 4 array of ones to a 3 by 4 array of twos, then multiply every element by 11. No loops. Print it.
2. `sin_values`: the sine of each element of `sequence_array`, using `np.sin`. Print it.
3. `rounded`: `sin_values` rounded to two decimal places, using `np.round`. Print it.

In [11]:
num_array=(np.ones((3,4))+np.ones((3,4)))*11
print(num_array)
sin_values=np.sin(sequence_array)
print(sin_values)
rounded=np.round(sin_values,2)
print(rounded)

[[22. 22. 22. 22.]
 [22. 22. 22. 22.]
 [22. 22. 22. 22.]]
[ 0.          0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111
 -0.53657292  0.99060736 -0.28790332 -0.75098725]
[ 0.    0.91 -0.76 -0.28  0.99 -0.54 -0.54  0.99 -0.29 -0.75]


## Final Check: Restart and Run All

1. Before you finish this lab, restart the kernel and run all cells to make sure everything still works. (Hint: there is a single command that does this.)
2. Check that every output is what you expect.
3. Upload the notebook to Moodle, and keep a copy in your own OneDrive.

If you finish the lab outside of class, we are still glad to see it. Show us during the next lab hour if you like.

### General Instructions for Labs

- If you do not finish during the lab hour, complete it as homework. **Labs are due at the start of the next class session.**
- A late lab earns reduced credit, capped at 60. Late work is accepted until the start of class on the day of the test covering this module, and not after.
- A file that is empty, corrupted, or will not open is not a submission. Replace it within 24 hours and it earns credit as late work.
- Moodle carries the official deadline. If a deadline ever changes, the change appears on Moodle first.