In [1]:
import numpy as np

In [63]:
scores = np.array([
    [88, 92, 85, 91, 84],   # Alice
    [78, 81, 79, 76, 74],   # Bob
    [94, 93, 90, 95, 91],   # Carol
    [70, 78, 65, 69, 67],   # David
])

In [64]:
students = ["Alice", "Bob", "Carol", "David"]
tests = ["Test1", "Test2", "Test3", "Test4", "Test5"]

In [65]:
scores.shape

(4, 5)

In [66]:
result=scores.sum(axis=1).sum()
print(result)

1640


In [67]:
highestScoreOnEachTest=np.argmax(scores,axis=1)

In [68]:
for items in highestScoreOnEachTest:
    print(tests[items])

Test2
Test2
Test4
Test2


In [69]:
product=scores.prod()
print(product)

-5320042544922329088


In [70]:
productNew=scores.astype(float).prod()
print(productNew)

1.6478221276603993e+38


In [71]:
scores.min(axis=0)

array([70, 78, 65, 69, 67])

In [72]:
students[scores[:,0].argmax()]

'Carol'

In [73]:
t=np.array([60,91,78,91])
t.max()
t.argmax()
np.where(t==t.max())

(array([1, 3]),)

In [74]:
(scores.sum(axis=1)/scores.shape[1]).round(0)

array([88., 78., 93., 70.])

In [75]:
scores.mean(axis=1)

array([88. , 77.6, 92.6, 69.8])

In [76]:
scores.std(axis=0).round(1)

array([ 9.2,  6.6,  9.4, 10.6,  9.2])

In [77]:
sorted(students,key= lambda student:student[1])

['Carol', 'David', 'Alice', 'Bob']

In [80]:
np.sort(scores)

array([[84, 85, 88, 91, 92],
       [74, 76, 78, 79, 81],
       [90, 91, 93, 94, 95],
       [65, 67, 69, 70, 78]])

In [79]:
scores

array([[88, 92, 85, 91, 84],
       [78, 81, 79, 76, 74],
       [94, 93, 90, 95, 91],
       [70, 78, 65, 69, 67]])

In [81]:
alice=scores[0]

In [84]:
alice>90

array([False,  True, False,  True, False])

In [85]:
alice[alice>90]

array([92, 91])

In [86]:
scores[scores.mean(axis=1) > 80]

array([[88, 92, 85, 91, 84],
       [94, 93, 90, 95, 91]])